apiVersion: v1
kind: Pod
metadata:
  name: mynginx-create
  labels:
    devops: '18'
    company: talent
spec:
  containers:
  - name: nginx
    image: nginx:1.20.1
    ports:
    - containerPort: 80
