apiVersion: v1
kind: Pod
metadata:
  name: pullpolicy-ifnotpresent
  labels:
    devops: '18'
    company: talent
  namespace: qa
spec:
  containers:
  - name: tomcat-never
    image: tomcat
    imagePullPolicy: IfNotPresent
  restartPolicy: Always

