apiVersion: v1
kind: Pod
metadata:
  name: mynginx-onfailure
  labels:
    devops: '18'
    company: talent
  namespace: qa
spec:
  containers:
  - name: nginx
    image: nginx:1.19.1
  restartPolicy: OnFailure
