apiVersion: v1
kind: Pod
metadata:
  name: pullpolicy-never
  labels:
    devops: '18'
    company: talent
  namespace: qa
spec:
  containers:
  - name: nginx-container
    image: nginx
    imagePullPolicy: Never
  restartPolicy: Always

