apiVersion: v1
kind: Pod
metadata:
  name: mynginx
  labels:
    devops: '18'
    company: talent
  namespace: dev
spec:
  containers:
  - name: nginx
    image: nginx:1.19.1
    ports:
    - containerPort: 80
