apiVersion: v1
kind: Pod
metadata:
  name: mynginx-cpu-memory
  labels:
    devops: '18'
    company: talent
  namespace: qa
spec:
  containers:
  - name: nginx
    image: nginx:1.19.1
    ports:
    - containerPort: 80
    resources:
      requests:
       cpu: 20m
       memory: 100Mi
      limits:
        cpu: 200m
        memory: 500Mi
