apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nodeselector
  labels:
    purpose: learning
  namespace: maloth
spec:
  replicas: 4
  selector:
    matchLabels:
      type: create
  template:
    metadata:
      name: httpd-test
      labels:
        devops: '18'
        company: talent
        type: create
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        ports:
        - containerPort: 80
      nodeSelector:
        tier: web


