apiVersion: apps/v1
kind: Deployment 
metadata:
  name: pod-affinity-test
  labels:
    purpose: learning
  namespace: marvel
spec:
  replicas: 2
  selector:
    matchLabels:
      type: create
  template:
    metadata:
      name: httpd-test
      labels:
        devops: '18'
        company: talent
        type: create
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        ports:
        - containerPort: 80
      nodeName: k8-worker3 
        


